# Generated by Django 5.2.4 on 2025-08-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=12, verbose_name='پسورد')),
            ],
            options={
                'verbose_name': 'ورود به حساب کاربری',
                'verbose_name_plural': 'ورود به حساب های کاربری',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل ها'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_name',
            field=models.CharField(max_length=20, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationalcode',
            field=models.CharField(max_length=12, verbose_name='کد ملی'),
        ),
    ]
