# Generated by Django 5.2.4 on 2025-07-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
